services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-app
    ports:
      - "8080:8080"
    volumes:
      - h2-data:/data
    environment:
      - TZ=America/Sao_Paulo
    restart: always

volumes:
  h2-data:
